### ISSUE TITLE
The automated release is failing 🚨

### ISSUE THREAD

**Issue by akaSybe** [akaSybe/rollup-plugin-svelte-ssr#3]
## :rotating_light: The automated release from the `master` branch failed. :rotating_light:

I recommend you give this issue a high priority, so other packages depending on you could benefit from your bug fixes and new features.

You can find below the list of errors reported by **semantic-release**. Each one of them has to be resolved in order to automatically publish your package. I’m sure you can resolve this 💪.

Errors are usually caused by a misconfiguration or an authentication problem. With each error reported below you will find explanation and guidance to help you to resolve it.

Once all the errors are resolved, **semantic-release** will release your package the next time you push a commit to the `master` branch. You can also manually restart the failed CI job that runs **semantic-release**.

If you are not sure how to resolve this, here is some links that can help you:
- [Usage documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/README.md)
- [Frequently Asked Questions](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md)
- [Support channels](https://github.com/semantic-release/semantic-release#get-help)

If those don’t help, or if this issue is reporting something you think isn’t right, you can always ask the humans behind **[semantic-release](https://github.com/semantic-release/semantic-release/issues/new)**.

---

### No npm token specified.

An [npm token](https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the `NPM_TOKEN` environment variable on your CI environment.

Please make sure to create an [npm token](https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the `NPM_TOKEN` environment variable on your CI environment. The token must allow to publish to the registry `https://registry.npmjs.org/`.

---

Good luck with your project ✨

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by akaSybe** [comment]
## :rotating_light: The automated release from the `master` branch failed. :rotating_light:

I recommend you give this issue a high priority, so other packages depending on you could benefit from your bug fixes and new features.

You can find below the list of errors reported by **semantic-release**. Each one of them has to be resolved in order to automatically publish your package. I’m sure you can resolve this 💪.

Errors are usually caused by a misconfiguration or an authentication problem. With each error reported below you will find explanation and guidance to help you to resolve it.

Once all the errors are resolved, **semantic-release** will release your package the next time you push a commit to the `master` branch. You can also manually restart the failed CI job that runs **semantic-release**.

If you are not sure how to resolve this, here is some links that can help you:
- [Usage documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/README.md)
- [Frequently Asked Questions](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md)
- [Support channels](https://github.com/semantic-release/semantic-release#get-help)

If those don’t help, or if this issue is reporting something you think isn’t right, you can always ask the humans behind **[semantic-release](https://github.com/semantic-release/semantic-release/issues/new)**.

---

### No npm token specified.

An [npm token](https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the `NPM_TOKEN` environment variable on your CI environment.

Please make sure to create an [npm token](https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the `NPM_TOKEN` environment variable on your CI environment. The token must allow to publish to the registry `https://registry.npmjs.org/`.

---

Good luck with your project ✨

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by mylastore** [comment]
so this will crawl pages for seo?

**Comment by akaSybe** [comment]
This plugin allows to get prerendered markup for Svelte component (not the whole page), if you want to get static pages for SEO, it would be better to use Sapper (https://sapper.svelte.dev/docs#Exporting)

**Comment by akaSybe** [comment]
@mylastore this plugin allows to get prerendered HTML-markup for Svelte component (not for the whole page). It's better to use Sapper (https://sapper.svelte.dev/docs#Exporting) to generate static pages for SEO

**Comment by mylastore** [comment]
> @mylastore this plugin allows to get prerendered HTML-markup for Svelte component (not for the whole page). It's better to use Sapper (https://sapper.svelte.dev/docs#Exporting) to generate static pages for SEO

ah ok, I been trying to find a router that support SSR just like Sapper. Would be nice to have something that could also generate the entire page at built time for SEO ;)

**Comment by akaSybe** [comment]
@mylastore Why don't you use Sapper? Looks like it's exactly what you want

**Comment by mylastore** [comment]
> @mylastore Why don't you use Sapper? Looks like it's exactly what you want

I created 90% of my website already using a router instead of Sapper, for me feels that I could do more with a router for example, I don't render a route at all if you need to be authorized and with Sapper I could not figure how to do that.

**Comment by akaSybe** [comment]
At work we are using nginx SSI directives to include parts of page, and we have header & footer as standalone applications, footer was rewritten using Svelte, that's why I had written this plugin as we need SEO for footer.

It looks like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
  </head>
  <body>
    <div id="page">
      <div id="header">
        <!--# include virtual="/ssi/header.html"-->
      </div>
      <div id="root"></div>
      <div id="footer">
        <!--# include virtual="/ssi/footer.html"-->
      </div>
  </body>
</html>
```

this plugin generates `footer.html` in CI pipeline and nginx inserts its content instead HTML-comment

**Comment by mylastore** [comment]
> At work we are using nginx SSI directives to include parts of page, and we have header & footer as standalone applications, footer was rewritten using Svelte, that's why I had written this plugin as we need SEO for footer.
> 
> It looks like this:
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>   </head>
>   <body>
>     <div id="page">
>       <div id="header">
>         
>       </div>
>       <div id="root"></div>
>       <div id="footer">
>         
>       </div>
>   </body>
> </html>
> ```
> 
> this plugin generates `footer.html` in CI pipeline and nginx inserts its content instead HTML-comment

Nice, very clever ;)
